export interface InternationalCandidateFormI {
  take_on_other_employement: string
  need_disability_related_adjustments: string
  health_support_needs: string
  post_applied: string
  title: string
  first_name: string
  last_name: string
  other_names: string
  home_phone: string
  mobile_phone: string
  email: string
  sex: string
  dob: string
  over_18: string
  nationality: string
  driving_license: string
  street_address: string
  city: string
  country: string
  zip_code: string
  passport: string
  photo_passport: string
  ielts_result: string
  proof_of_covid_vaccination: string
  evidence_of_TB_test_result: string
  ever_convicted_of_a_criminal_offence: string
  pending_prosecutions: string
  registered_disabled: string
  education_date_obtained: string
  education_place_of_study: string
  education_grade: string
  other_qualification_date_obtained: string
  other_qualification_place_of_study: string
  other_qualification_grade: string
  previous_name_of_employer: string
  previous_employer_address: string
  previous_employment_length: string
  previous_employment_salary: string
  previous_employement_start_date: string
  previous_employement_end_date: string
  previous_employment_duties: string
  previous_employment_required_weeks_notice: string
  previous_employment_reason_for_leaving: string
  referee_name1: string
  referee_job_title1: string
  referee_company_name1: string
  referee_address_1: string
  referee_email_1: string
  referee_phone_1: string
  can_contact_reference1: string
  referee_name_2: string
  referee_job_title_2: string
  referee_company_name_2: string
  referee_address_2: string
  referee_email_2: string
  referee_phone_2: string
  can_contact_reference_2: string
  personal_attributes: string
  sign_full_name: string
  sign_date: string
  can_hold_details: string
  cv: string
  ethnicity: string
  gender: string
  age_group: string
  emergency_contact_first_name: string
  emergency_contact_last_name: string
  emergency_contact_phone: string
  emergency_contact_email: string
  emergency_contact_address: string
}
